<template>
  <div
    class="input__container mt-1-rem mr-2-rem"
    :style="`width: ${width ? width : 300}px`"
  >
    <div class="input">
      <input
        :id="id"
        :type="isPassword ? 'password' : isNumber ? 'number' : 'text'"
        :readonly="readOnly"
        v-model="val"
        @input="$emit('update-value', $event.target.value)"
      />
      <label v-if="label" :for="id">{{ label }}</label>
      <span class="append" v-if="append">{{ append }}</span>
      <span class="append">
        <slot name="append"></slot>
      </span>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return { val: "" };
  },
  props: {
    width: Number,
    isNumber: Boolean,
    isPassword: Boolean,
    id: String,
    label: String,
    authorizedCars: Array,
    maxWidth: Number,
    append: String,
    readOnly: Boolean,
    value: String,
  },
  watch: {
    value(val) {
      this.val = val;
    },
  },
  mounted() {
    this.val = this.$props.value;
  },
};
</script>

<style scoped lang="scss">
@import "../../../css/variables.scss";
$background: lighten($lavander, 8%);

/* ----------------------------------------------
 * Generated by Animista on 2021-7-19 9:43:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@keyframes slide-top {
  0% {
    background-color: $background;
    font-size: 0.8rem;
    top: -0.75em;
    left: 0.5em;
  }
  100% {
    background-color: none;
    font-size: 1rem;
    top: -1.5em;
    left: -0.25em;
  }
}
@keyframes slide-down {
  0% {
    background-color: none;
    font-size: 1rem;
    top: -1.5em;
    left: -0.25em;
  }
  100% {
    background-color: $background;
    font-size: 0.8rem;
    top: -0.75em;
    left: 0.5em;
  }
}

.input__container {
  width: 100%;
}

.input {
  $color: $purple;
  clear: both;
  padding-top: 1rem;
  color: $color;
  height: 2rem;
  position: relative;
  width: calc(100% - 1rem);

  label,
  input {
    padding: 0.3em 0.4em 0.3em 0.4em;
    margin: 0;
    background: $background;
    border-radius: 0.2rem;
    position: absolute;
    left: 0;
    top: 0;
  }
  input + label {
    top: -0.75em;
    left: 0.5em;
    padding: 0.1em 0.3em 0.1em 0.3em;
    font-size: 0.8rem;
  }
  input[readonly="false"] + label {
    -webkit-animation: slide-down 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: slide-down 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
  input {
    border: solid 1px $color;
    min-height: 1rem;
    width: 100%;

    &:hover {
      border: solid 1px lighten($color, 25%);
    }

    &:hover + label {
      color: lighten($color, 25%);
    }

    &[readonly="false"]:focus {
      border: solid 2px darken($color, 1%);
      outline: none;
      margin-left: -1px;
      margin-top: -1px;

      & + label {
        color: darken($color, 1%);
        font-size: 1rem;
        background: none;
        -webkit-animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
          both;
        animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      }
    }
  }

  .append {
    position: absolute;
    left: calc(100% + 1rem);
    top: 0;
    display: inline-block;
    line-height: 1rem;
    margin-top: 0.3rem;
    margin-left: 0.2rem;
  }
}
</style>